openapi: 3.0.0
info:
  title: 7ofus site interaction
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /login:
    post:
      summary: Login user into the site
      tags: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: user id registered in the site
                password:
                  type: string
                  description: password regsistered in the site
              required:
                - id
                - password
  /register:
    post:
      summary: Login user into the site
      tags: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: 'user id '
                name:
                  type: string
                  description: user name
                email:
                  type: string
                  description: user email address
                password:
                  type: string
                  description: user password
              required:
                - id
                - name
                - email
                - password
components:
  schemas: {}
